namespace TasksManagement.Commands.Enums;
public enum CommandType
{
    CreateTeam,
    CreateBoard,
    CreateMember,
    CreateBug,
    CreateStory,
    CreateFeedback,
    ShowAllMembers,
    ShowTeams,
    ShowMembers,
    ShowBoards,
    ShowActivity,
    ChangeStatus,
    ChangePriority,
    ChangeAssignee,
    ChangeSeverity,
    ChangeSize,
    ChangeRating,
    ListTasks,
    ListBugs,
    ListStories,
    ListFeedback,
    ListAssigned,
}
